FROM node:6-alpine

WORKDIR /appbackend

COPY package.json .

RUN npm install --production --silent

COPY *.js ./
COPY public ./public/
COPY views ./views/
COPY routes ./routes/

EXPOSE 3000

CMD node app.js
